import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  stepCardWrap: { width: "100%", marginBottom: 16 },
  collapsibleCard: { padding: 0 },
  stepHeader: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 15,
    overflow: "hidden",
  },
  stepNumber: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumberText: { fontFamily: "Inter_700Bold", fontSize: 15 },
  stepHeadingCopy: { flex: 1, minWidth: 0 },
  stepTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 18 },
  stepSubtitle: { fontFamily: "Inter_400Regular", fontSize: 11, lineHeight: 16, marginTop: 2 },
  stepChevron: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  stepContent: { gap: 14, paddingHorizontal: 18, paddingBottom: 18 },
  kidGallery: { gap: 12 },
  galleryTabs: { marginHorizontal: -20 },
  galleryTabsContent: { paddingHorizontal: 20, gap: 8 },
  galleryTab: {
    minHeight: 38,
    maxWidth: 190,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  galleryTabText: { fontFamily: "Inter_700Bold", fontSize: 12 },
  kidHeading: { flexDirection: "row", alignItems: "center", gap: 8 },
  kidTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 19 },
  kidSwipeHint: { fontFamily: "Inter_600SemiBold", fontSize: 10, marginTop: 2 },
  kidCarousel: { marginHorizontal: -20, overflow: "visible" },
  kidGalleryContent: { paddingHorizontal: 20, paddingRight: 48, gap: 12 },
  kidPictureShell: { borderRadius: 24, borderWidth: 2, overflow: "hidden" },
  kidPicture: { width: "100%", padding: 8 },
  kidImage: { width: "100%", aspectRatio: 1.45, borderRadius: 17 },
  kidCardFooter: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 6,
    paddingTop: 8,
    paddingBottom: 3,
  },
  kidName: { flex: 1, minWidth: 0, fontFamily: "Inter_700Bold", fontSize: 14, lineHeight: 18 },
  kidSelectIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  kidPagination: {
    height: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  kidDot: { height: 7, borderRadius: 99 },
  packLibraryButton: {
    minHeight: 72,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  packLibraryIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  packLibraryTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 15 },
  packLibraryMeta: { fontFamily: "Inter_400Regular", fontSize: 10, lineHeight: 14, marginTop: 2 },
  orDivider: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 2 },
  orLine: { flex: 1, height: StyleSheet.hairlineWidth },
  orText: { fontFamily: "Inter_700Bold", fontSize: 9, letterSpacing: 1.1 },
  detectedFormat: {
    minHeight: 68,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  detectedFormatIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  detectedFormatCopy: { flex: 1, minWidth: 0 },
  detectedFormatTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 14 },
  detectedFormatMeta: { fontFamily: "Inter_600SemiBold", fontSize: 10, marginTop: 2 },
  difficultyHero: {
    minHeight: 112,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  difficultyHeroIcon: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: "rgba(5,12,28,.28)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  difficultyHeroCopy: { flex: 1, minWidth: 0 },
  difficultyHeroLabel: { color: "#08111f", fontFamily: "BricolageGrotesque_700Bold", fontSize: 22 },
  difficultyHeroMeta: {
    color: "rgba(8,17,31,.68)",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    marginTop: 3,
  },
  difficultyHeroCount: {
    color: "#08111f",
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontSize: 35,
    lineHeight: 37,
    textAlign: "right",
  },
  difficultyHeroUnit: {
    color: "rgba(8,17,31,.68)",
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 1,
    textAlign: "right",
  },
  slider: { height: 48, justifyContent: "center", marginTop: 3 },
  sliderLine: { position: "absolute", left: 14, right: 14, height: 5, borderRadius: 99 },
  sliderMarks: {
    position: "absolute",
    left: 10,
    right: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sliderMark: { width: 9, height: 9, borderRadius: 5, borderWidth: 2 },
  sliderThumb: {
    position: "absolute",
    left: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    padding: 3,
  },
  sliderThumbInner: { flex: 1, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  sliderFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -2,
  },
  sliderEndpoint: { fontFamily: "Inter_700Bold", fontSize: 11 },
  sliderHint: { fontFamily: "Inter_600SemiBold", fontSize: 10 },
});
