import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 52, paddingBottom: 132 },
  hero: { borderWidth: 1, padding: 20, marginBottom: 27, overflow: "hidden" },
  heroCopy: { paddingRight: 62 },
  kicker: { fontFamily: "Inter_700Bold", fontSize: 11, letterSpacing: 1.7 },
  heading: {
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontSize: 29,
    lineHeight: 34,
    marginTop: 7,
  },
  heroDescription: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 7,
  },
  heroIcon: {
    position: "absolute",
    right: 18,
    top: 18,
    width: 51,
    height: 51,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  statsRow: { flexDirection: "row", gap: 10, marginTop: 18 },
  stat: {
    flex: 1,
    minWidth: 0,
    minHeight: 46,
    borderRadius: 15,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  statValue: { fontFamily: "BricolageGrotesque_800ExtraBold", fontSize: 17 },
  statLabel: { minWidth: 18, fontFamily: "Inter_600SemiBold", fontSize: 10 },
  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 14,
  },
  sectionKicker: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 1.7,
  },
  sectionTitle: {
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontSize: 24,
    lineHeight: 29,
    marginTop: 4,
  },
  livePill: {
    height: 31,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  liveDot: { width: 7, height: 7, borderRadius: 4 },
  liveText: { fontFamily: "Inter_700Bold", fontSize: 10 },
  list: { gap: 11 },
  friendCard: {
    width: "100%",
    minHeight: 98,
    borderWidth: 1,
    overflow: "hidden",
  },
  friendTouchArea: { width: "100%" },
  friendContent: {
    width: "100%",
    minHeight: 98,
    paddingHorizontal: 13,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  rankMark: {
    width: 43,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
  },
  rank: { fontFamily: "BricolageGrotesque_800ExtraBold", fontSize: 18 },
  rankOnTrophy: { position: "absolute", top: 24, fontSize: 13 },
  avatarRing: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    padding: 3,
  },
  avatar: {
    flex: 1,
    borderRadius: 25,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  online: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
    right: -1,
    bottom: 2,
    borderWidth: 3,
  },
  friendCopy: { flex: 1, minWidth: 0 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  name: { flexShrink: 1, fontFamily: "Inter_700Bold", fontSize: 15 },
  youPill: { borderRadius: 7, paddingHorizontal: 6, paddingVertical: 3 },
  youText: { fontFamily: "Inter_700Bold", fontSize: 8, letterSpacing: 0.8 },
  status: { fontFamily: "Inter_400Regular", fontSize: 10, marginTop: 4 },
  progressTrack: {
    height: 4,
    borderRadius: 2,
    overflow: "hidden",
    marginTop: 8,
  },
  progressFill: { height: "100%", borderRadius: 2 },
  xp: { minWidth: 43, alignItems: "flex-end" },
  xpValue: { fontFamily: "BricolageGrotesque_800ExtraBold", fontSize: 18 },
  xpLabel: { fontFamily: "Inter_700Bold", fontSize: 9, letterSpacing: 0.6 },
  invite: {
    borderWidth: 1,
    padding: 14,
    marginTop: 15,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  inviteIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  inviteCopy: { flex: 1, minWidth: 0 },
  inviteTitle: { fontFamily: "Inter_700Bold", fontSize: 13 },
  inviteDescription: {
    fontFamily: "Inter_400Regular",
    fontSize: 10,
    marginTop: 3,
  },
  shareButton: {
    width: 43,
    height: 43,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  shareTouchArea: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  empty: {
    borderWidth: 1,
    padding: 25,
    alignItems: "center",
    gap: 12,
    overflow: "hidden",
  },
  errorCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  errorText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
  },
  socialTools: {
    borderWidth: 1,
    padding: 15,
    gap: 14,
    overflow: "hidden",
    marginBottom: 24,
  },
  codeRow: { flexDirection: "row", alignItems: "center", gap: 11 },
  codeIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  codeLabel: { fontFamily: "Inter_700Bold", fontSize: 8, letterSpacing: 1.1 },
  codeValue: {
    fontFamily: "BricolageGrotesque_800ExtraBold",
    fontSize: 19,
    letterSpacing: 1.8,
    marginTop: 2,
  },
  codeShare: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  searchRow: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    gap: 9,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    paddingVertical: 12,
  },
  searchButton: {
    width: 46,
    height: 46,
    marginRight: 4,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  socialSection: { marginBottom: 24, gap: 11 },
  compactList: { gap: 9 },
  noResults: {
    textAlign: "center",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    marginTop: -10,
    marginBottom: 22,
  },
  manageFriend: {
    marginTop: 7,
    width: 28,
    height: 22,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontFamily: "BricolageGrotesque_700Bold",
    fontSize: 21,
    textAlign: "center",
  },
  emptyCopy: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginBottom: 5,
  },
  pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
});
