import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: { alignSelf: "stretch", marginBottom: 30, width: "100%" },
  sectionTitle: { fontFamily: "Inter_700Bold", fontSize: 12, letterSpacing: 1.4, marginBottom: 13 },
  language: { flexDirection: "row", borderWidth: 1, padding: 4 },
  languageOption: { flex: 1, minHeight: 48, alignItems: "center", justifyContent: "center" },
  languageText: { fontFamily: "Inter_700Bold", fontSize: 16 },
  themePressable: { width: 174, height: 150 },
  themeCard: {
    flex: 1,
    borderWidth: 1.5,
    padding: 14,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  themeStripe: { position: "absolute", left: 0, right: 0, top: 0, height: 6 },
  themeIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  themeName: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 18 },
  themeDescription: { fontFamily: "Inter_600SemiBold", fontSize: 10, marginTop: 3 },
  rewardedBadge: {
    position: "absolute",
    top: 14,
    left: 12,
    minHeight: 25,
    borderRadius: 13,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  rewardedBadgeText: { fontFamily: "Inter_700Bold", fontSize: 8, letterSpacing: 0.35 },
  check: {
    position: "absolute",
    top: 14,
    right: 12,
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  group: { borderWidth: 1, overflow: "hidden" },
  settingRow: {
    minHeight: 72,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  settingText: { flex: 1, fontFamily: "Inter_600SemiBold", fontSize: 16 },
  switchSlot: { width: 62, minHeight: 48, alignItems: "flex-end", justifyContent: "center" },
  switch: { transform: [{ scaleX: 0.88 }, { scaleY: 0.88 }] },
  tourGroup: { marginBottom: 12 },
  helpRow: { alignSelf: "flex-start", flexDirection: "row", alignItems: "stretch", gap: 12 },
  helpPressable: { width: "100%", minWidth: 0 },
  help: {
    width: "100%",
    minHeight: 154,
    borderWidth: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    padding: 16,
  },
  helpIcon: {
    width: 47,
    height: 47,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  helpText: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 17 },
  helpSubtitle: { fontFamily: "Inter_600SemiBold", fontSize: 10, marginTop: 3 },
  pressed: { opacity: 0.68, transform: [{ scale: 0.98 }] },
  danger: {
    minHeight: 64,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    gap: 12,
    overflow: "hidden",
  },
  dangerText: { flex: 1, minWidth: 0, fontFamily: "Inter_700Bold", fontSize: 17 },
  dangerIcon: {
    width: 28,
    height: 28,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  dangerDisabled: { opacity: 0.38 },
  premiumCard: { borderWidth: 1, padding: 18, gap: 14, overflow: "hidden" },
  premiumHeader: { flexDirection: "row", alignItems: "center", gap: 13 },
  premiumIcon: {
    width: 50,
    height: 50,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  premiumTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 21 },
  premiumSubtitle: { fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 18, marginTop: 3 },
  benefits: { gap: 9 },
  benefit: { flexDirection: "row", alignItems: "center", gap: 9 },
  benefitText: { flex: 1, fontFamily: "Inter_600SemiBold", fontSize: 13 },
  planGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap", gap: 10 },
  planOption: {
    flex: 1,
    minWidth: "45%",
    minHeight: 148,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    paddingTop: 17,
    paddingBottom: 14,
    overflow: "hidden",
  },
  planBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: 10,
  },
  planBadgeText: { fontFamily: "Inter_700Bold", fontSize: 8, letterSpacing: 0.7 },
  planTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  planTitle: { flex: 1, fontFamily: "BricolageGrotesque_700Bold", fontSize: 17 },
  planRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  planRadioDot: { width: 10, height: 10, borderRadius: 5 },
  planPrice: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 22, marginTop: 10 },
  planCadence: { fontFamily: "Inter_600SemiBold", fontSize: 9, lineHeight: 13, marginTop: 2 },
  planEquivalent: { fontFamily: "Inter_700Bold", fontSize: 10, marginTop: 7 },
  parentNote: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  monetizationError: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  ageCard: {
    minHeight: 82,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  ageCopy: { flex: 1, minWidth: 0, justifyContent: "center" },
  ageTitle: { fontFamily: "Inter_600SemiBold", fontSize: 16, lineHeight: 21 },
  ageDescription: { fontFamily: "Inter_400Regular", fontSize: 11, lineHeight: 16, marginTop: 2 },
});
