import { Ionicons } from "@expo/vector-icons";
import { StyleSheet, Switch, Text, View } from "react-native";
import { AppHeader, Card, Screen } from "@/components/pieceful-ui";
import { mobileThemes } from "@/constants/pieceful-theme";
import { type MobilePreferences, useApp } from "@/state/app-provider";

export default function AccessibilityScreen() {
  const { preferences, t, theme } = useApp();
  const colors = mobileThemes[theme];
  return <Screen><AppHeader title={t("Acessibilidade", "Accessibility")} showTitle back /><Card style={styles.intro}><View style={[styles.heroIcon, { backgroundColor: colors.panelAlt }]}><Ionicons name="accessibility" size={30} color={colors.accent} /></View><View style={{ flex: 1 }}><Text style={[styles.title, { color: colors.text }]}>{t("Jogue do seu jeito", "Play your way")}</Text><Text style={[styles.copy, { color: colors.muted }]}>{t("Ajustes aplicados imediatamente à interface.", "Settings are applied to the interface immediately.")}</Text></View></Card><Card style={{ padding: 0, overflow: "hidden" }}><PreferenceRow icon="contrast-outline" title={t("Alto contraste", "High contrast")} description={t("Realça bordas, botões e estados de foco.", "Emphasizes borders, buttons, and focus states.")} setting="highContrast" value={preferences.highContrast} /><PreferenceRow icon="remove-circle-outline" title={t("Movimento reduzido", "Reduced motion")} description={t("Desativa entradas e fundos animados.", "Disables animated entrances and backgrounds.")} setting="reducedMotion" value={preferences.reducedMotion} last /></Card></Screen>;
}

function PreferenceRow({ icon, title, description, setting, value, last = false }: { icon: keyof typeof Ionicons.glyphMap; title: string; description: string; setting: keyof MobilePreferences; value: boolean; last?: boolean }) { const { theme, updatePreference } = useApp(); const colors = mobileThemes[theme]; return <View style={[styles.row, { borderBottomColor: `${colors.muted}28`, borderBottomWidth: last ? 0 : StyleSheet.hairlineWidth }]}><View style={[styles.rowIcon, { backgroundColor: colors.panelAlt }]}><Ionicons name={icon} size={22} color={colors.accent} /></View><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.rowDescription, { color: colors.muted }]}>{description}</Text></View><View style={styles.switchSlot}><Switch value={value} onValueChange={(next) => updatePreference(setting, next)} ios_backgroundColor={colors.panelAlt} trackColor={{ false: colors.panelAlt, true: `${colors.accent}bb` }} thumbColor={value ? colors.text : colors.muted} style={styles.switch} /></View></View>; }

const styles = StyleSheet.create({ intro: { flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 16 }, heroIcon: { width: 58, height: 58, borderRadius: 18, alignItems: "center", justifyContent: "center" }, title: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 22 }, copy: { fontFamily: "Inter_400Regular", fontSize: 13, lineHeight: 18, marginTop: 3 }, row: { minHeight: 104, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, paddingVertical: 14 }, rowIcon: { width: 43, height: 43, borderRadius: 14, alignItems: "center", justifyContent: "center" }, rowTitle: { fontFamily: "Inter_700Bold", fontSize: 15 }, rowDescription: { fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 17, marginTop: 3 }, switchSlot: { width: 58, alignItems: "flex-end" }, switch: { transform: [{ scaleX: .86 }, { scaleY: .86 }] } });
