import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  toolbar: {
    marginHorizontal: 12,
    marginTop: 6,
    borderRadius: 25,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    overflow: "hidden",
  },
  timerRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  timerText: { fontFamily: "Inter_700Bold", fontSize: 12, fontVariant: ["tabular-nums"] },
  workspaceLoading: {
    minHeight: 420,
    borderWidth: 1,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 28,
  },
  workspaceLoadingTitle: {
    fontFamily: "BricolageGrotesque_700Bold",
    fontSize: 21,
    marginTop: 5,
  },
  workspaceLoadingText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    textAlign: "center",
  },
  zoomControls: {
    position: "absolute",
    right: 16,
    bottom: 264,
    zIndex: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  zoomButtonDisabled: { opacity: 0.38 },
  storeLooseControl: {
    position: "absolute",
    left: 16,
    bottom: 264,
    zIndex: 72,
    flexDirection: "column",
    gap: 8,
  },
  pieceStoredNotice: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 266,
    zIndex: 90,
    minHeight: 58,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  pieceStoredNoticeIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  pieceStoredNoticeText: {
    flexShrink: 1,
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    lineHeight: 19,
    textAlign: "center",
  },
  hintFollowNotice: {
    position: "absolute",
    alignSelf: "center",
    top: 128,
    zIndex: 90,
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 10,
  },
  referenceBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "rgba(2,5,16,.84)",
  },
  referenceCard: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "82%",
    padding: 14,
    borderRadius: 26,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 18,
  },
  referenceHeader: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  referenceTitle: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 19 },
  referenceSubtitle: { fontFamily: "Inter_400Regular", fontSize: 11, lineHeight: 16, marginTop: 2 },
  referenceImageStage: { width: "100%", alignItems: "center", justifyContent: "center" },
  referenceImage: { maxWidth: "100%", borderRadius: 18, overflow: "hidden" },
});
