import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  sheet: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 0,
    zIndex: 80,
    borderWidth: 1.5,
    borderRadius: 26,
    overflow: "hidden",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -10 },
    elevation: 18,
  },
  header: {
    height: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  headerIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCopy: { flex: 1, minWidth: 0 },
  title: { fontFamily: "BricolageGrotesque_700Bold", fontSize: 15 },
  meta: { fontFamily: "Inter_600SemiBold", fontSize: 9, marginTop: 2 },
  storage: {
    width: 43,
    height: 43,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
  },
  selectionBadge: {
    minWidth: 42,
    height: 32,
    paddingHorizontal: 8,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  selectionCount: { fontFamily: "Inter_700Bold", fontSize: 12 },
  divider: { height: 1 },
  filters: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  filterButton: {
    flex: 1,
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  filterLabel: { fontFamily: "Inter_700Bold", fontSize: 12 },
  pieceList: { height: 124, flexGrow: 0 },
  pageScroller: { flex: 1 },
  page: {
    height: 124,
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "center",
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  pieceCell: { alignItems: "center", justifyContent: "center" },
  pagination: {
    height: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingBottom: 4,
  },
  dot: { height: 6, borderRadius: 99 },
  pageCount: { marginLeft: 4, fontFamily: "Inter_700Bold", fontSize: 9 },
  stackLayer: {
    position: "absolute",
    inset: 7,
    borderRadius: 12,
    borderWidth: 1.5,
    backgroundColor: "rgba(18,27,55,.88)",
  },
  stackLayerBack: { transform: [{ translateX: 8 }, { translateY: -7 }, { rotate: "7deg" }] },
  stackLayerMiddle: { transform: [{ translateX: 4 }, { translateY: -4 }, { rotate: "3deg" }] },
  selectedOutline: {
    position: "absolute",
    inset: 2,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#67edf3",
  },
  selectedCheck: {
    position: "absolute",
    top: -7,
    right: -7,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#67edf3",
  },
  dragOverlay: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 300,
    elevation: 30,
    shadowOpacity: 0.55,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
  },
  dragStack: {
    position: "absolute",
    inset: 8,
    borderRadius: 12,
    borderWidth: 1.5,
    backgroundColor: "rgba(12,20,44,.92)",
  },
  dragStackBack: { transform: [{ translateX: 10 }, { translateY: -8 }, { rotate: "8deg" }] },
  dragStackMiddle: { transform: [{ translateX: 5 }, { translateY: -4 }, { rotate: "4deg" }] },
  dragCount: {
    position: "absolute",
    right: -10,
    top: -10,
    zIndex: 4,
    minWidth: 25,
    height: 25,
    borderRadius: 13,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  dragCountText: { color: "#071126", fontFamily: "Inter_800ExtraBold", fontSize: 11 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 9 },
  emptyText: { fontFamily: "Inter_600SemiBold", fontSize: 12 },
});
