import { Ionicons } from "@expo/vector-icons";
import { StyleSheet, Text, View } from "react-native";
import { AppHeader, Card, Screen } from "@/components/pieceful-ui";
import { mobileThemes } from "@/constants/pieceful-theme";
import { useApp } from "@/state/app-provider";

export default function ControllerHelpScreen() { const { t, theme } = useApp(); const colors = mobileThemes[theme]; return <Screen><AppHeader title={t("Controles", "Controllers")} showTitle back /><View style={styles.platforms}><Platform icon="logo-xbox" name="Xbox" /><Platform icon="logo-playstation" name="PlayStation" /></View><Card style={{ padding: 0, overflow: "hidden" }}><ControlRow symbol="L" title={t("Mover peça", "Move piece")} description={t("Analógico esquerdo ou direcional", "Left stick or directional pad")} /><ControlRow symbol="A / ✕" title={t("Selecionar e soltar", "Pick up and drop")} description={t("Botão inferior do controle", "Bottom face button")} /><ControlRow symbol="X / □" title={t("Girar peça", "Rotate piece")} description={t("Gira 90 graus", "Rotates 90 degrees")} /><ControlRow symbol="Y / △" title={t("Referência", "Reference")} description={t("Exibe a imagem original", "Shows the original image")} last /></Card><Text style={[styles.note, { color: colors.muted }]}>{t("Conecte o controle por Bluetooth antes de abrir o quebra-cabeça.", "Connect the controller over Bluetooth before opening the puzzle.")}</Text></Screen>; }
function Platform({ icon, name }: { icon: keyof typeof Ionicons.glyphMap; name: string }) { const { theme } = useApp(); const colors = mobileThemes[theme]; return <View style={[styles.platform, { backgroundColor: colors.panel, borderColor: `${colors.accent}35`, borderRadius: colors.radius }]}><Ionicons name={icon} size={28} color={colors.accent} /><Text style={[styles.platformName, { color: colors.text }]}>{name}</Text></View>; }
function ControlRow({ symbol, title, description, last = false }: { symbol: string; title: string; description: string; last?: boolean }) { const { theme } = useApp(); const colors = mobileThemes[theme]; return <View style={[styles.row, { borderBottomColor: `${colors.muted}28`, borderBottomWidth: last ? 0 : StyleSheet.hairlineWidth }]}><View style={[styles.key, { backgroundColor: colors.panelAlt, borderColor: `${colors.accent}55` }]}><Text style={[styles.keyText, { color: colors.accent }]}>{symbol}</Text></View><View style={{ flex: 1 }}><Text style={[styles.title, { color: colors.text }]}>{title}</Text><Text style={[styles.description, { color: colors.muted }]}>{description}</Text></View></View>; }
const styles = StyleSheet.create({ platforms: { flexDirection: "row", gap: 12, marginBottom: 16 }, platform: { flex: 1, minHeight: 92, borderWidth: 1, alignItems: "center", justifyContent: "center", gap: 8 }, platformName: { fontFamily: "Inter_700Bold", fontSize: 14 }, row: { minHeight: 78, flexDirection: "row", alignItems: "center", gap: 14, paddingHorizontal: 15, paddingVertical: 10 }, key: { minWidth: 54, height: 42, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 }, keyText: { fontFamily: "Inter_700Bold", fontSize: 13 }, title: { fontFamily: "Inter_700Bold", fontSize: 15 }, description: { fontFamily: "Inter_400Regular", fontSize: 12, marginTop: 3 }, note: { fontFamily: "Inter_600SemiBold", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 16, paddingHorizontal: 20 } });
